### ISSUE TITLE
Not working if not gmail

### ISSUE THREAD

**Issue by airdogvan** [AnalogJ/hatchet#10]
I tried with another mail provider and got the following response:
INFO[0000] Connecting to server...                       type=email
INFO[0000] Connected                                     type=email
INFO[0000] Logged in                                     type=email
INFO[0000] Mailbox name: [Gmail]/All Mail                type=email
FATA[0000] Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).  type=email

Is there a way I could connect with other services than Gmail?

**Comment by AnalogJ** [comment]
yep, Hatchet supports multiple CLI options you can use to configure a different IMAP provider and inbox name:

https://github.com/AnalogJ/hatchet/blob/main/cmd/hatchet/hatchet.go#L110-L131
