### ISSUE TITLE
Feature request: progress bar

### ISSUE THREAD

**Issue by lury** [AnalogJ/hatchet#4]
Hi,

could you add a progress bar to the app?
like this one: https://github.com/schollz/progressbar

app is running - no idea how long it'll take, no flushes of results to csv, so progress indicator would be useful :)

Thanks for this app!
Regards,

**Comment by AnalogJ** [comment]
This is a great idea. Implemented via https://github.com/AnalogJ/hatchet/commit/4ec7496c73f94125fa48c9442f7672601c372a3a and released in v0.0.4

Thanks!

**Comment by lury** [comment]
release 0.0.5 broke progressbar - and also any previous output on windows.

release 0.0.4 works ok

**Comment by AnalogJ** [comment]
thats weird. nothing in https://github.com/AnalogJ/hatchet/compare/v0.0.4...v0.0.5 should be windows specific. 
can you run hatchet with `--debug` and attach some of the initialization logs here (removing any private information)?
