### ISSUE TITLE
Report Not Created When Using Docker

### ISSUE THREAD

**Issue by oldjohngalt** [AnalogJ/hatchet#7]
I am a docker newbie, but I think there might be an error in the docker run command.  

It ran successfully but I couldn't find the report file.  Without persistent storage is the report deleted since the -rm tag is used?

Perhaps the report is just hidden somewhere and I can't find it.

**Comment by AnalogJ** [comment]
ah. You'll need to do a volume mount from the container to your local machine.

```
docker run --rm -v `pwd`:/out/ \
    ghcr.io/analogj/hatchet:latest report \
    --output-path="/out/sender_report.csv" \
    --imap-hostname=imap.gmail.com \
    --imap-username=xxxxx@gmail.com \
    --imap-password=xxxxxxx
```

I'll update the readme momentarily.
